### ISSUE TITLE
Is there something wrong about the equation?

### ISSUE THREAD

**Issue by sonrisa07** [distillpub/post--understanding-gnns#10]
<img width="370" alt="截屏2023-11-10 16 25 40" src="https://github.com/distillpub/post--understanding-gnns/assets/146523929/392ca26d-e6c5-4451-b2ae-43f3f08061d1">

Should there be $D_v\ x$ instead of $D_v\ x_v$ on the last line? 
According to the article mentioned above, $x_v$ is a scalar but $D_v$ is a vector.

line reference:
https://github.com/distillpub/post--understanding-gnns/blob/917b5ea81966de18a08600a3acdb809b009ef478/public/index.html#L623

**Comment by ameya98** [comment]
So $D_v = \sum_u A_{vu}$ as mentioned in the article above. Note that $D$ is a diagonal matrix of degrees, and $D_v$ is the degree of node $v$. So this looks okay to me.
