### ISSUE TITLE
Found 404 link

### ISSUE THREAD

**Issue by ZiminPark** [distillpub/post--understanding-gnns#5]
I found 404 link at "Understanding Convolutions on Graphs" -> "Supplementary Material" -> "Reproducing Experiments" ->  first link at "Spectral Representations of Natural Images".
I guess you might want to link https://distill.pub/2021/understanding-gnns/#spectral.
Thanks for your amazing article. It really helps me to understand the concept of GNN.
<img width="880" alt="스크린샷 2021-10-29 오후 6 36 38" src="https://user-images.githubusercontent.com/48933016/139412825-bd5ecceb-68e2-4539-92bb-03df6e869205.png">

**Comment by ameya98** [comment]
Thank you! We have fixed this now.

**Comment by ameya98** [comment]
@ncammarata is it possible to re-upload our article with this fix now?

**Comment by ncammarata** [comment]
deployed!
