### ISSUE TITLE
Notational typo

### ISSUE THREAD

**Issue by jspencer12** [distillpub/post--understanding-gnns#6]
In the section titled: Polynomial Filters are Node-Order Equivariant - Details for the Interested Reader 

On the second-to-last math line of the greyed box, there is an x' at the end of the expression, which I believe should simply be an x. x' would imply that it had been operated on by L or P, but the P^T P matrices from the previous line cancel to identity and the other P matrix is pulled out front. Thus, there has just been a reorganization of the matrices with no actual operations, leaving x unchanged.

**Comment by ameya98** [comment]
Yes, you are absolutely correct. Thanks for catching this! I've sent in a fix.

**Comment by ameya98** [comment]
@ncammarata Can we upload the latest version of the article? Thanks in advance!
